### ISSUE TITLE
[RFE] Add an embedded_vulnerability key

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#34]
A lot of these issues are related to packages that are embedding libraries. It would be useful to have a key that can take a name of the external library that the vulnerability is in.

**Comment by briandfoy** [comment]
Yeah, go for it. Maybe something like:

```
embedded_vulnerability: true
embedded_library:
    name: libfoo
    source: https://www.github.com/some_author/libfoo
    affected_version:  # library version, not Perl module version
    fix_version:
```

We don't do anything with that, but it's better to have it for later.
