### ISSUE TITLE
Clean up embedded and external vulnerability metadata

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#46]
These should be combined, with a flag to indicate whether it is embedded. See https://github.com/briandfoy/cpan-security-advisory/issues/37#issuecomment-1172502973

**Comment by briandfoy** [comment]
We should have something like this once we have some time to get everything else under control. Since we don't do anything in cpan-audit with these data, this can wait a bit.

Here's the structure I suggested:

```
external_vunerability:
   name: ...
   affected_versions: ...
   fixed_versions: ...
   embedded: {true|false}
```

But, I think I also suggested tracking these separately from the Perl module advisories. We'd then come up with a way to include those:

```
external_vunerability: externals/libfoo-001.yml 
```

Right now we are collecting and organizing data even though we don't have the code there. If we have the data, in any form, we can convert it latter if we find a better way to use it. Eventually this is probably going to have to be relational.

**Comment by briandfoy** [comment]
There's a new thing that I'm doing, which I'll have to document later when it settles down to a point where I like it. 

Each external library gets its own file under *external_reports/*, such as *external_reports/jquery.yml*. That has all the info for all of the CVEs and advisories for jquery. This way, we aren't repeating the same thing over and over again in several files under *cpansa/*.

Then we can simply list the affected perl distros, their versions, and which version of the external library they distribute. This is a lot easier than checking over lots of separate files. Once I get this part done, I'll write some stuff to turn this into stuff the database module can use:

```
---
name: jquery
perl_distributions:
  - name: Sidef
    affected:
      - perl_module_versions:
        distributed_library_version: '2.1.3'
  - name: Stardust
    affected:
      - perl_module_versions:
        distributed_library_version: '2.1.3'
```
